name: Comb-p CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pip-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository Content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip