name: Comb-p CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pip-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository Content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute test.sh script
        run: |
          chmod +x /home/runner/work/combined-pvalues/combined-pvalues/cpv/bin/bedtools
          ./test.sh