name: Comb-p CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pip-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository Content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create bedtools alias and make it available to the container
        run: |
          echo $PWD
          alias bedtools="$PWD/cpv/bin/bedtools"
          chmod +x ./cpv/bin/bedtools

      - name: Execute test.sh script
        run: ./test.sh